export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
export const ADD_CART_FROM_LOCAL_STORAGE = "ADD_CART_FROM_LOCAL_STORAGE"
export const CHANGE_QUANTITY_OF_CART_PRODUCT = "CHANGE_QUANTITY_OF_CART_PRODUCT"
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART"
